apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module
    version: '13.5'
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: FreeBSD
            version: "13.5"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/freebsd-org-cloud-dev/global/images/freebsd-13-5-release-amd64-gce
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-west1-c
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-standard
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 20
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: n2d-standard-2
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue:
          - EPHEMERAL
      - name: enable_cloud_api
        description: Allow full access to all of Google Cloud Platform APIs on the VM
        varType: bool
        defaultValue: true
      - name: enable_cloud_logging
        description: Enables Cloud Logging.
        varType: bool
        defaultValue: true
      - name: enable_cloud_monitoring
        description: Enables Cloud Monitoring.
        varType: bool
        defaultValue: true
    outputs:
      - name: instance_machine_type
        description: Machine type for the compute instance.
      - name: instance_nat_ip
        description: External IP of the compute instance.
      - name: instance_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.
